[2022-09-07 11:23:45,157] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: user_processing.creating_table 2022-09-06T00:00:00+00:00 [queued]>
[2022-09-07 11:23:45,167] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: user_processing.creating_table 2022-09-06T00:00:00+00:00 [queued]>
[2022-09-07 11:23:45,167] {taskinstance.py:1017} INFO - 
--------------------------------------------------------------------------------
[2022-09-07 11:23:45,167] {taskinstance.py:1018} INFO - Starting attempt 1 of 1
[2022-09-07 11:23:45,167] {taskinstance.py:1019} INFO - 
--------------------------------------------------------------------------------
[2022-09-07 11:23:45,205] {taskinstance.py:1038} INFO - Executing <Task(SqliteOperator): creating_table> on 2022-09-06T00:00:00+00:00
[2022-09-07 11:23:45,209] {standard_task_runner.py:51} INFO - Started process 30486 to run task
[2022-09-07 11:23:45,230] {standard_task_runner.py:75} INFO - Running: ['airflow', 'tasks', 'run', 'user_processing', 'creating_table', '2022-09-06T00:00:00+00:00', '--job-id', '3', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpeprjodsy']
[2022-09-07 11:23:45,231] {standard_task_runner.py:76} INFO - Job 3: Subtask creating_table
[2022-09-07 11:23:45,337] {logging_mixin.py:103} INFO - Running <TaskInstance: user_processing.creating_table 2022-09-06T00:00:00+00:00 [running]> on host airflowvm
[2022-09-07 11:23:45,456] {taskinstance.py:1230} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=creating_table
AIRFLOW_CTX_EXECUTION_DATE=2022-09-06T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-06T00:00:00+00:00
[2022-09-07 11:23:45,457] {sqlite.py:63} INFO - Executing: 
            CREATE TABLE users(
                email TEXT NOT NULL PRIMARY KEY,
                firstname TEXT NOT NULL,
                lastname TEXT NOT NULL,
                country TEXT NOT NULL,
                username TEXT NOT NULL,
                password TEXT NOT NULL
            );
            
[2022-09-07 11:23:45,476] {base.py:65} INFO - Using connection to: id: db_sqlite. Host: /home/airflow/airflow/airflow.db, Port: None, Schema: , Login: , Password: XXXXXXXX, extra: None
[2022-09-07 11:23:45,477] {dbapi.py:180} INFO - Running statement: 
            CREATE TABLE users(
                email TEXT NOT NULL PRIMARY KEY,
                firstname TEXT NOT NULL,
                lastname TEXT NOT NULL,
                country TEXT NOT NULL,
                username TEXT NOT NULL,
                password TEXT NOT NULL
            );
            , parameters: []
[2022-09-07 11:23:45,479] {taskinstance.py:1396} ERROR - table users already exists
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1086, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1260, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1300, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/sqlite/operators/sqlite.py", line 65, in execute
    hook.run(self.sql, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/dbapi.py", line 184, in run
    cur.execute(sql_statement)
sqlite3.OperationalError: table users already exists
[2022-09-07 11:23:45,485] {taskinstance.py:1433} INFO - Marking task as FAILED. dag_id=user_processing, task_id=creating_table, execution_date=20220906T000000, start_date=20220907T112345, end_date=20220907T112345
[2022-09-07 11:23:45,567] {local_task_job.py:118} INFO - Task exited with return code 1
